### ISSUE TITLE
StoryMap: design, prep, test, deliver

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/PuertoRicoWaterStudies#18]
@jphuong @miguelcleon 
Lets figure out the story, and then get the GIS data ready?  
Or vice versa?
Inventory the data we have now and tell a story?

**Comment by ChristinaB** [comment]
See @darctur's work on http://cuahsi.maps.arcgis.com/apps/MapSeries/index.html?appid=e201458acbce4b17a9139fd25c278116

**Comment by darctur** [comment]
The Harvey data & story were iterative, but it worked better when I started with the GIS data, then developed the story map after the uploaded GIS data were reasonably complete and had stable organization. As I uploaded the datasets, the hierarchy of collections > subcollections > composite resources evolved somewhat. This drove the story map organization. Also, some of the GIS data were too complex or dense for quick display in the story map. For those I used the story map narrative panel to list the datasets and put screenshots of the more complex ones. I used the map frame for the simpler GIS layers and to identify regional boundaries for spatial context (counties & HUC6 bounds). Your mileage will vary since the Maria story is broader in scope than the Harvey story.

**Comment by darctur** [comment]
Btw, I'm starting now on the Irma datasets and story map, but these will be more sparse; we don't have as much of the data we had for Harvey.

**Comment by miguelcleon** [comment]
hello @darctur thanks for the tips. Where did you get the wind swath data?   Seems like I could assemble it from here https://www.nhc.noaa.gov/gis/archive_forecast_info_results.php?id=al15&year=2017&name=Hurricane%20MARIA but it would be alot of merging shapefiles.

**Comment by darctur** [comment]
@miguelcleon I used the wind swath data from the "Best Track" which was smoothed in comparison with the advisories. You can get the [Best Tracks here](https://www.nhc.noaa.gov/data/tcr/index.php?season=2017&basin=atl). The shapefile has all the instances. For greatest path detail, you could scrape it from the [Advisories here](https://www.nhc.noaa.gov/archive/2017/MARIA.shtml?) but it'd be a bit of work.

**Comment by miguelcleon** [comment]
Ok great, thank you @darctur ! @ChristinaB I think I'll put up a story map with just the hurricane path and windfield to get started. @jphuong do you have access to push GIS data to the CUAHSI ArcGIS server?

**Comment by darctur** [comment]
@miguelcleon @jphuong If you are using ArcGIS Pro, you can directly publish to the CUAHSI AGOL server from the ArcPro map document. If that's of interest I could show you how I did that using a web call with screensharing, just need to pick a time.

**Comment by miguelcleon** [comment]
@darctur yup, I've done that, I don't know if @jphuong has though. I've gotten the [story map with the single tab up](https://arcg.is/00f1ij).  I used the same text since it seems like generic text that should be included with all of these 2017 Hurricane story maps. We can make changes this is just a start.

**Comment by darctur** [comment]
@miguelcleon Great, that's a start! I'm not fussed about you copying that part of the text, but the text colors don't work well on a gray background. Also, I tried clicking on Maria track points, but didn't get a popup. Be sure to configure popups and edit the display names for the fields so they're like normal readable text instead of abbreviated names with caps and underscores. You'll probably also have to change some numeric fields like the storm magnitude to remove default 2-decimal places.

**Comment by miguelcleon** [comment]
I configured the hurricane Maria advisory points. Looks like I need to change the attribute table field aliases in the source to make the field names more readable. So that seems to involve making the change in arcgis desktop and then overwriting the service. But maybe I'm missing some way to do that in the online map viewer @darctur ? Thanks for your help.

**Comment by darctur** [comment]
@miguelcleon You don't need to change it in the desktop and re-upload unless you just want to. But can do it in the AGOL map with the uploaded data, and I find that interface friendlier. You can also reorder and de-select any attributes that are "true but useless" or "too much info".

1. Edit story map > edit tab map > configure popups
![01-story map edit - map edit - config popus](https://user-images.githubusercontent.com/2423101/40142354-fbae7fde-591d-11e8-9385-4cb542bf5887.png)

2. Configure attributes
![02-config attribs](https://user-images.githubusercontent.com/2423101/40142368-069cea52-591e-11e8-8587-3cc42767ef05.png)

3. Set the attribute label text and formats
![03-set attrib text formats](https://user-images.githubusercontent.com/2423101/40142114-5db033ea-591d-11e8-967c-e917c829d7b9.png)

If it would help to have a screen-share session to talk about this, let me know.

**Comment by miguelcleon** [comment]
@darctur ok, I didn't realize you could type in there, yeah that is simpler.

**Comment by ChristinaB** [comment]
https://napsg.maps.arcgis.com/apps/StoryMapCrowdsource/index.html?appid=78b819db2f1446b0ac7c93252a53c5ff

Yeah!!!!!

**Comment by miguelcleon** [comment]
@ChristinaB @jphuong I've added two tabs, one for the crowd sourced images and one with NOAA post Maria images the map is here https://arcg.is/00f1ij

**Comment by darctur** [comment]
Looking good so far, but the NOAA post-Maria tab stays blank for me… is this a permissions thing or content not yet in place?  

Also, I’ve edited the logo & links in upper-right of story map frame, please refresh if you have the story map open. Hope that’s ok, can re-do if needed.

dka
 

On May 22, 2018, at 3:45 PM, Miguel Leon <notifications@github.com> wrote:

@ChristinaB <https://github.com/ChristinaB> @jphuong <https://github.com/jphuong> I've added two tabs one for the crowd sourced images and one with NOAA post Maria images the map is here https://arcg.is/00f1ij <https://arcg.is/00f1ij>

**Comment by miguelcleon** [comment]
@darctur looks good, thanks! So for the NOAA tab it is an issue of mixing content between HTTP and HTTPS. I'm not sure if there is a solution, it seems like I might just have to have an external link to it.

**Comment by darctur** [comment]
@miguelcleon  Pretty sure it needs to be https to work. Also, check your popup config for the storm tracks: need to remove commas & decimal points from year and date-time fields for all three storms, eg: 
Date Time, UTC | 2,017,082,000.00
Year | 2,017.00

**Comment by miguelcleon** [comment]
@darctur , yeah looks like your right. Good point, Ive removed the commas and decimal points.

**Comment by ChristinaB** [comment]
@miguelcleon 
Please see https://drive.google.com/open?id=1rOJll-DQx1FFOSMs4PxD8VGcoOQPfeQw
for landslides and health data (starter maps).

**Comment by ChristinaB** [comment]
For the upper logo, we have https://www.cuahsi.org/projects/hurricanes-2017-data-archive
but we also can put https://www.cuahsi.org/projects/maria2017
I'm trying  to use #maria2017 in all our hydroshare tags for the RAPID project

**Comment by miguelcleon** [comment]
I've added several additional tabs, I think it is pretty good now. Although there are probably a few minor edits that would be helpful.

**Comment by darctur** [comment]
@miguelcleon Two issues jump out to me: (1) the narrative panel on the left is too wide for its intended function; obscures much of the maps. See the [Harvey story map](http://arcg.is/001jje) for a narrower narrative panel layout style. (2) The new maps with a lot of features are way too cluttered & unreadable till you zoom in enough. Story maps don't let users turn on/off individual feature layers, only the story map author can do that. I'm open to other options on this, but for the Harvey maps I made the dense feature layers only appear when you zoom in enough to distinguish them. Then I put screenshots of each feature map (one layer per map) in the narrative panel for statewide view.  See Storm Track, Flood Data, Hydrology tabs in the [Harvey story map](http://arcg.is/001jje) for examples.

**Comment by miguelcleon** [comment]
@darctur Ok thanks for taking a look. I changed (1) your right, this looks better. For (2) yeah, I see what your saying, I'm not sure what the solution is though. I'd be worried people wouldn't realize they could see the data in the map if I went with the approach you suggest.

**Comment by miguelcleon** [comment]
@ChristinaB for the NAPSG 'Maria Stories' tab, it looks like they are no longer accepting submissions. Their documentation discusses a '+ photo' button that no longer appears on that map.

**Comment by ChristinaB** [comment]
That's a bummer. I guess it's not exactly in our scope of work to follow up on that. We would have to contact NAPSG via CUAHSI and see how to set up an ongoing photo collection.  @Lizabrazil may have had citizen science projects in mind that would also benefit from that kind of relationship.

**Comment by darctur** [comment]
Same thing with the Harvey photo collection. It still seems worth posting for historical viewing. I heard about that from Paul Doherty at NAPSG, will follow up with him by separate email. 

On May 25, 2018, at 2:11 PM, Christina Bandaragoda <notifications@github.com> wrote:

That's a bummer. I guess it's not exactly in our scope of work to follow up on that. We would have to contact NAPSG via CUAHSI and see how to set up an ongoing photo collection. @Lizabrazil <https://github.com/Lizabrazil> may have had citizen science projects in mind that would also benefit from that kind of relationship.

**Comment by miguelcleon** [comment]
@darctur I think clustering points is probably a better option for reducing clutter. I'm looking into it.

**Comment by darctur** [comment]
@miguelcleon  I'd like to do some clustering on a couple of my maps too, let me know how you do that if you figure it out. Another approach to de-clutter is saving the map when it's zoomed in just far enough for the key features to be easily distinguishable. My [Harvey story map](http://arcg.is/001jje) is near completion now, have a look. My densest layers are rasters or polygons, too big for web viewing over the whole area. Clustering wouldn't help these, but it would help with the high water marks and stream gages.  

I also added a "Data Index" tab, with direct links to all relevant HydroShare resources and ftp sites (TACC). 

Comments, corrections, suggestions welcome!

**Comment by miguelcleon** [comment]
@darctur Ok, I figured out how to cluster points. The data you want to cluster has to be hosted on AGOL as a feature layer service, instead of being hosted on the CUAHSI ArcGIS Server. Like [this one ](https://services7.arcgis.com/M1GdIfrBNFtdTD7r/arcgis/rest/services/FEMA_Damge_assessments_Public/FeatureServer/0?token=QgOUB29PnKU0Ly5SYJtYMyM3Zcndkx2Z9P6Q3A9bURAhtGZd5gH_y309jliEp_LOTfHXsAMhrM6IJCyNpL_NcV89OR_Pf439IQzrIYJBwcxy_UjAQu3DswJD2nv3y0hydkIRiU0AWbNkosztpg-BdrEYnbuJu0HqQUQPv4DFtBu1XwdAKvhbhZUUKAhROSWRRT1z7NynmoGAwhCAAmX0z7wrmr4QTDAWkP5m4HKDqC9eux98KOpfCHM9x_lYJEy6) The property and infrastructuredamage tab now has clustering based on this feature layer service. Maria story map: https://arcg.is/00f1ij

**Comment by miguelcleon** [comment]
Hi @darctur and @ChristinaB I have added clustering to layers on two of the tabs. I'm satisfied with the clutter level, although if there are strong opinions I could add more. I'd like to close this issue if there are no objections.

**Comment by darctur** [comment]
@miguelcleon  Glad you figured out the clustering, but I don't quite see what you do after hosting the data as a feature layer service. Is it a symbolization option in AGOL?  Btw, in your linked service, Damage is misspelled (FEMA_Damge_assessments_Public). Also, the clustering works for Prop/Infra map, but it would help to include the number of clustered instances, as done with the photos in the crowdsource photo map. 

I have some comments on other tabs: 
**Power outages tab**: this is an external map, much like the crowdsource photos, and doesn't fit well in the Maria story map. Your narrative pane covers part of it. It's also not primary data for a the HydroShare resource, is it? I would make it a simple link in a narrative pane for a tab like "Maria Stories", and let the user open it in a new tab from there. See [Harvey Stories](http://arcg.is/001jje) tab for examples. I've tried every way I could to improve embedded map layouts, but it works best just to open in a new tab. 

**Map legends**:  you have the legends at bottom of the narrative panes. Users may not see them. Another option is to make them a pulldown (Map Series overall settings > Layout options). 

**Limited Mobility tab**: this lacks a legend, and really needs one. The narrative pane obscures the map navigation tools and title. The map seems readable enough otherwise. Suggest republishing the feature layers with your own AGOL map for better integration with the story map. 

**Health tab**: this needs cartographic help; very busy, discordant symbologies. If clustering, use much simpler symbols (eg, than Rx), and put number of instances as a number in the cluster symbol rather than scaling by size. 

**Data Index**: add a tab for a data index to the HydroShare collections, see [Harvey data index tab](http://arcg.is/001jje) for example. 

**User support**: Add this at bottom of narrative panes for your supported data layers (see Harvey tabs for example): 
Issues or comments? Please report any errors, gaps, issues, or requests relevant to this story map and the related HydroShare data pages to help@cuahsi.org.

@ChristinaB  Sorry for all the comments, let me know if I can help with any of these.

**Comment by miguelcleon** [comment]
@darctur thanks for the feedback it is much appreciated. 

For clustering you need a hosted feature layer like this: 
![image](https://user-images.githubusercontent.com/5941108/41623216-09984058-73e0-11e8-9385-240134036862.png)

Add the hosted feature layer to your web map and you should get a clustering option 
![image](https://user-images.githubusercontent.com/5941108/41623740-b669878c-73e1-11e8-93a6-0cec22519ef0.png)

Here are some more detailed instructions https://doc.arcgis.com/en/arcgis-online/create-maps/configure-clustering.htm

**Comment by miguelcleon** [comment]
@darctur Also I don't see any option to show the number of items clustered like in the photo map. If it is there I haven't been able to find it.

**Comment by darctur** [comment]
I don’t see it yet either. I’m checking with Paul Doherty. It may be built into that crowdsource photo app. 

On Jun 19, 2018, at 4:23 PM, Miguel Leon <notifications@github.com> wrote:

@darctur <https://github.com/darctur> Also I don't see any option to show the number of items clustered like in the photo map. If it is there I haven't been able to find it.

**Comment by darctur** [comment]
@miguelcleon @ChristinaB  I've found how to avoid obscuring the map frame with the narrative panel, which was a problem for tabs that used external web apps like Power Outages and Limited Mobility etc. I fixed it by setting the frame width as custom-percentage instead of using "Fill" option, see graphic below.  When your Description Panel setting is "small" you can use 80% frame width on web apps like Power Outages, Limited Mobility etc, and the Harvey Crowdsource Photos web app. If you have your Description Panel setting as "medium" then 70% width works. 
![fixing poweroutage frame width](https://user-images.githubusercontent.com/2423101/41752457-2def8a7a-758d-11e8-9604-ab22c77afce9.png)

**Comment by darctur** [comment]
@miguelcleon @ChristinaB  I also moved the Legend to be a pulldown (upper-right corner of map frames) instead of below the narrative text. I'm still concerned about the cartography of the maps for Limited Mobility and Health tabs. These are cluttered, and the only legend for the Limited Mobility map is found by opening the feature layer in the Layers list, rather than under Legend as one would expect; suggest having this layer list/legend open by default when opening the map. The Health map symbologies are confusing without studying the legend. This map seems better suited to a Web App Builder app, that would let the user turn layers on or off. 

Paul Doherty showed me more options for clustering features, as in the Property Damage and Health maps. With these basic AGOL maps, this is about all you can do. To get something more like what's in the NAPSG Crowdsource Photos app, you need to use WebAppBuilder (see Info Summary widget), and even maybe custom coding. I've decided not to do clustering in my maps. I have few enough features over a very large area. But I may adapt some maps to the WebAppBuilder so I can let the user turn on/off some layers.

**Comment by miguelcleon** [comment]
>

>  User support: Add this at bottom of narrative panes for your supported data layers (see Harvey tabs for example):
> Issues or comments? Please report any errors, gaps, issues, or requests relevant to this story map and the related HydroShare data pages to help@cuahsi.org.
> 

@darctur Ok, this is done

>  I've found how to avoid obscuring the map frame with the narrative panel, which was a problem for tabs that used external web apps like Power Outages and Limited Mobility etc.

great thank you. 

It looks like you changed the Limited Mobility tab to use a webAppBuilder map, I added the legend and removed the feature layer widget. I changed the style and I think it's somewhat better now, I'm not too concerned about the clutter. However, nothing shows up in the tab when I browse this layer in chrome while not logged into arcgisonline so that is a serious problem.

**Comment by miguelcleon** [comment]
@darctur I removed the pharmacy layer from the health tab to reduce clutter. That didn't really add any useful information. Thanks.

**Comment by darctur** [comment]
@miguelcleon  Thanks, and the legend for the Limited Mobility tab is easier to find now. I still recommend a Data Links tab that lists all the HS resources included in the Maria collection, similar to the Harvey story map Data Links tab. You could include relevant links in the narrative pane for tabs showing content that can be downloaded from HS. 

There's also a FEMA resource I don't see mentioned, have a look and see if you might create a HS resource page and story map tab for the data here: https://data.femadata.com/NationalDisasters/HurricaneMaria/
https://data.femadata.com/FIMA/NHRAP/Maria/

**Comment by miguelcleon** [comment]
Yeah, a data resource page looks like a good idea. I created one.

**Comment by darctur** [comment]
But don't leave out the direct links to your HydroShare resource pages. Did you look at the Data Links tab on my [Harvey story map](http://cuahsi.maps.arcgis.com/apps/MapSeries/index.html?appid=e201458acbce4b17a9139fd25c278116)?

**Comment by miguelcleon** [comment]
@darctur No, I guess I just ran with the general idea, I needed to leave the office but I wanted to get something up quick. I added a number of Hydroshare links at the top now. Thanks.

**Comment by darctur** [comment]
@miguelcleon  Looks good! you could add the "Issues or comments" blurb below the list of links on the Data Resources tab. Also, I thought you'd fixed the Limited Mobility map to show its legend, but I'm not seeing its legend now, just a Legend pulldown that's empty.

**Comment by miguelcleon** [comment]
@darctur Yup, Ok should be fixed now.

**Comment by miguelcleon** [comment]
Ok, it's ready for distribution. Thanks for all your help!

**Comment by darctur** [comment]
@miguelcleon @ChristinaB Looks fine, glad to help!
